export class facturacionelectronicaventa {
    constructor(
      public IdVenta: number,
      public IdCita: number,
      public Cita: string,
      public IdCaja: number,  
      public Caja: string,
      public NumeroDocumento: string,  
      public IdTipoDocumento: string,    
      public TipoDocumento: string,
      public Serie: string,  
      public Numero: string,
      public IdCliente: string,  
      public Cliente: string,   
      public IdMoneda: string,   
      public Moneda: string, 
      public IdEstadoDocumento: string,   
      public EstadoDocumento: string,     
      public IdFormulario: string, 
      public Formulario: string,
      public IdEstadoFE: string,
      public EstadoFE: string,
      public FechaRegistro: string,  
      public pDescuento: string, 
      public pRecargo: string,  
      public pPrecioBase: string,    
      public pAbono: string, 
      public pVuelto: string, 
      public pTotal: string,
      public pEfectivos: string,
      public pSuttotal: string,
      public pIgv: string,
      public IdTipoPago: string,
      public TipoPago: string,
      public CodigoOperacion: string,
      public FechaPago: string,
      public UsuarioRegistra: string
    ) {  }
  
  }